# Generated by Django 4.2.9 on 2026-03-07 19:44

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=500)),
                ("full_name", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=1000)),
                ("clone_url", models.URLField(blank=True, max_length=1000)),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("watchers", models.IntegerField(default=0)),
                ("open_issues", models.IntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=100)),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("owner", models.CharField(max_length=200)),
                ("is_trending", models.BooleanField(default=False)),
                ("readme_summary", models.TextField(blank=True)),
                ("embedding_id", models.CharField(blank=True, max_length=200)),
                ("scraped_at", models.DateTimeField(auto_now=True)),
                ("repo_created_at", models.DateTimeField(blank=True, null=True)),
                ("stars_today", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "repositories",
                "ordering": ["-stars"],
                "indexes": [
                    models.Index(
                        fields=["language"], name="repositorie_languag_9b73bf_idx"
                    ),
                    models.Index(
                        fields=["is_trending"], name="repositorie_is_tren_e9a479_idx"
                    ),
                    models.Index(fields=["stars"], name="repositorie_stars_bc6715_idx"),
                ],
            },
        ),
    ]
