# Generated by Django 5.2.12 on 2026-04-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0006_repository_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="contributor_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="is_rising_star",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_commit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="star_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="repository",
            name="stars_30d_delta",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="stars_7d_delta",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="trend_class",
            field=models.CharField(
                choices=[
                    ("rising_star", "Rising Star"),
                    ("stable", "Stable"),
                    ("declining", "Declining"),
                ],
                db_index=True,
                default="stable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="velocity_30d",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="repository",
            name="velocity_7d",
            field=models.FloatField(default=0.0),
        ),
    ]
