# Generated by Django 4.2.29 on 2026-03-31 12:43

import uuid

import pgvector.django.vector

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('text', models.TextField()),
                ('author_username', models.CharField(db_index=True, max_length=200)),
                ('author_display_name', models.CharField(blank=True, max_length=300)),
                ('author_profile_image', models.URLField(blank=True, max_length=500)),
                ('author_verified', models.BooleanField(default=False)),
                ('author_followers', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('quote_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('mentions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('media_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, size=None)),
                ('is_retweet', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('is_quote', models.BooleanField(default=False)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('in_reply_to_user', models.CharField(blank=True, max_length=200)),
                ('lang', models.CharField(blank=True, max_length=10)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('source_label', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=100)),
                ('trending_score', models.FloatField(db_index=True, default=0.0)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tweets',
                'ordering': ['-posted_at', '-scraped_at'],
                'indexes': [models.Index(fields=['trending_score'], name='tweets_trendin_f6ced2_idx'), models.Index(fields=['posted_at'], name='tweets_posted__833271_idx'), models.Index(fields=['author_username'], name='tweets_author__4de3d0_idx'), models.Index(fields=['topic'], name='tweets_topic_8d8d9e_idx')],
            },
        ),
    ]
