# Generated by Django 5.2.12 on 2026-04-07 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_tweet_embedding_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="scraped_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
