# Generated by Django 5.2.12 on 2026-04-08 13:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_orgauditlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ["joined_at"], "verbose_name": "Membership"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created_at"], "verbose_name": "Organization"},
        ),
        migrations.AlterModelOptions(
            name="organizationinvite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Organization Invite",
            },
        ),
        migrations.AlterModelOptions(
            name="orgauditlog",
            options={"ordering": ["-timestamp"], "verbose_name": "Org Audit Log"},
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
