# Generated by Django 5.2.12 on 2026-03-30 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "core",
            "0005_rename_core_conver_user_id_idx_core_conver_user_id_3e2a4b_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["interaction_type"], name="ua_interaction_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "interaction_type"], name="ua_user_interaction_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbookmark",
            index=models.Index(fields=["user", "content_type"], name="ub_user_ct_idx"),
        ),
        migrations.AddIndex(
            model_name="userbookmark",
            index=models.Index(
                fields=["user", "created_at"], name="ub_user_created_idx"
            ),
        ),
    ]
