# Generated by Django 5.2.12 on 2026-04-03 21:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("coding", "Coding"),
                            ("writing", "Writing"),
                            ("analysis", "Analysis"),
                            ("business", "Business"),
                            ("creative", "Creative"),
                        ],
                        default="research",
                        max_length=50,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prompt_templates",
                "ordering": ["-upvotes", "-use_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvote_records",
                        to="agents.prompttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prompt_upvotes",
            },
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["category", "-upvotes"], name="pt_cat_upvotes_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["author", "-created_at"], name="pt_author_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["is_public", "-created_at"], name="pt_public_created_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promptupvote",
            unique_together={("user", "prompt")},
        ),
    ]
