# Generated by Django 5.2.12 on 2026-03-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_conversation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="core_conver_user_id_3e2a4b_idx",
            old_name="core_conver_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="core_conver_convers_00ff04_idx",
            old_name="core_conver_conv_id_idx",
        ),
    ]
