# Generated by Django 5.2.12 on 2026-04-04 05:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_daily_briefing"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=300)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("paper", "Paper"),
                            ("repository", "Repository"),
                            ("author", "Author"),
                            ("tool", "Tool"),
                            ("organization", "Organization"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("source_ids", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "mention_count",
                    models.PositiveIntegerField(db_index=True, default=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "knowledge_nodes",
                "ordering": ["-mention_count"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "-mention_count"],
                        name="kn_type_mentions_idx",
                    )
                ],
                "unique_together": {("name", "entity_type")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("cites", "Cites"),
                            ("uses", "Uses"),
                            ("authored_by", "Authored By"),
                            ("related_to", "Related To"),
                            ("built_with", "Built With"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("evidence", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="core.knowledgenode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="core.knowledgenode",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_edges",
                "indexes": [
                    models.Index(
                        fields=["source", "relation_type"], name="ke_source_rel_idx"
                    ),
                    models.Index(
                        fields=["target", "relation_type"], name="ke_target_rel_idx"
                    ),
                ],
                "unique_together": {("source", "target", "relation_type")},
            },
        ),
    ]
