# Generated by Django 5.2.12 on 2026-08-08 18:56

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticCacheEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(db_index=True, default="default", max_length=64),
                ),
                ("prompt", models.TextField(max_length=4000)),
                (
                    "prompt_embedding",
                    pgvector.django.vector.VectorField(dimensions=1024),
                ),
                ("response", models.TextField()),
                ("hits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Semantic Cache Entry",
                "verbose_name_plural": "Semantic Cache Entries",
                "db_table": "semantic_cache_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "created_at"],
                        name="semantic_ca_scope_cf3543_idx",
                    )
                ],
            },
        ),
        # ANN index for the cosine-distance lookup. Without it every cache
        # read is a sequential scan over the whole table, which would make the
        # cache slower than the LLM call it exists to avoid.
        # Guarded so it is safe on backends/databases where the table or
        # pgvector extension is absent (e.g. the SQLite test DB).
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_name='semantic_cache_entries'
                    ) THEN
                        EXECUTE 'CREATE INDEX IF NOT EXISTS semantic_cache_embedding_ivfflat_idx
                                 ON semantic_cache_entries
                                 USING ivfflat (prompt_embedding vector_cosine_ops)
                                 WITH (lists = 100)';
                    END IF;
                END $$;
            """,
            reverse_sql="DROP INDEX IF EXISTS semantic_cache_embedding_ivfflat_idx;",
        ),
    ]
