# Generated by Django 5.2.12 on 2026-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_generateddocument_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('word', 'Word'), ('markdown', 'Markdown'), ('html', 'HTML'), ('project', 'Project Scaffold')], max_length=20),
        ),
    ]
