# Generated by Django 4.2.9 on 2026-03-07 19:44

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("github", "GitHub"),
                            ("arxiv", "arXiv"),
                            ("youtube", "YouTube"),
                            ("blog", "Blog"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("scrape_interval_minutes", models.IntegerField(default=30)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("author", models.CharField(blank=True, max_length=300)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("topic", models.CharField(blank=True, max_length=100)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("trending_score", models.FloatField(default=0.0)),
                ("view_count", models.IntegerField(default=0)),
                ("embedding_id", models.CharField(blank=True, max_length=200)),
                ("url_hash", models.CharField(blank=True, max_length=64, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.source",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-published_at", "-scraped_at"],
                "indexes": [
                    models.Index(fields=["topic"], name="articles_topic_9800a6_idx"),
                    models.Index(
                        fields=["trending_score"], name="articles_trendin_0ef557_idx"
                    ),
                    models.Index(
                        fields=["published_at"], name="articles_publish_73ad5f_idx"
                    ),
                    models.Index(fields=["source"], name="articles_source__bca100_idx"),
                ],
            },
        ),
    ]
