# Generated by Django 4.2.9 on 2026-03-07 19:44

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("youtube_id", models.CharField(max_length=50, unique=True)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("channel_name", models.CharField(blank=True, max_length=300)),
                ("channel_id", models.CharField(blank=True, max_length=300)),
                ("url", models.URLField(max_length=1000)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True)),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("embedding_id", models.CharField(blank=True, max_length=200)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "videos",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["published_at"], name="videos_publish_8b16cf_idx"
                    ),
                    models.Index(
                        fields=["channel_name"], name="videos_channel_08c1fb_idx"
                    ),
                ],
            },
        ),
    ]
