# Generated by Django 4.2.9 on 2026-03-07 19:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("ppt", "PowerPoint"),
                            ("word", "Word"),
                            ("markdown", "Markdown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("cloud_url", models.URLField(blank=True, max_length=1000)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("agent_prompt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "generated_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
