# Generated by Django 5.2.12 on 2026-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateddocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("ppt", "PowerPoint"),
                    ("word", "Word"),
                    ("markdown", "Markdown"),
                    ("project", "Project Scaffold"),
                ],
                max_length=20,
            ),
        ),
    ]
