import scrapy


class ArticleItem(scrapy.Item):
    title = scrapy.Field()
    url = scrapy.Field()
    content = scrapy.Field()
    author = scrapy.Field()
    published_at = scrapy.Field()
    source_name = scrapy.Field()
    source_url = scrapy.Field()
    source_type = scrapy.Field()
    tags = scrapy.Field()
    metadata = scrapy.Field()
    _is_existing = scrapy.Field()


class RepositoryItem(scrapy.Item):
    github_id = scrapy.Field()
    name = scrapy.Field()
    full_name = scrapy.Field()
    description = scrapy.Field()
    url = scrapy.Field()
    clone_url = scrapy.Field()
    stars = scrapy.Field()
    forks = scrapy.Field()
    watchers = scrapy.Field()
    open_issues = scrapy.Field()
    language = scrapy.Field()
    topics = scrapy.Field()
    owner = scrapy.Field()
    stars_today = scrapy.Field()
    is_trending = scrapy.Field()
    repo_created_at = scrapy.Field()
    metadata = scrapy.Field()
    _is_existing = scrapy.Field()


class ResearchPaperItem(scrapy.Item):
    arxiv_id = scrapy.Field()
    title = scrapy.Field()
    abstract = scrapy.Field()
    authors = scrapy.Field()
    categories = scrapy.Field()
    published_date = scrapy.Field()
    url = scrapy.Field()
    pdf_url = scrapy.Field()
    metadata = scrapy.Field()
    _is_existing = scrapy.Field()


class VideoItem(scrapy.Item):
    youtube_id = scrapy.Field()
    title = scrapy.Field()
    description = scrapy.Field()
    channel_name = scrapy.Field()
    channel_id = scrapy.Field()
    url = scrapy.Field()
    thumbnail_url = scrapy.Field()
    duration_seconds = scrapy.Field()
    view_count = scrapy.Field()
    like_count = scrapy.Field()
    published_at = scrapy.Field()
    topics = scrapy.Field()
    metadata = scrapy.Field()
    _is_existing = scrapy.Field()


class TweetItem(scrapy.Item):
    tweet_id = scrapy.Field()
    text = scrapy.Field()
    author_username = scrapy.Field()
    author_display_name = scrapy.Field()
    author_profile_image = scrapy.Field()
    author_verified = scrapy.Field()
    author_followers = scrapy.Field()
    retweet_count = scrapy.Field()
    like_count = scrapy.Field()
    reply_count = scrapy.Field()
    quote_count = scrapy.Field()
    view_count = scrapy.Field()
    bookmark_count = scrapy.Field()
    posted_at = scrapy.Field()
    hashtags = scrapy.Field()
    mentions = scrapy.Field()
    media_urls = scrapy.Field()
    urls = scrapy.Field()
    is_retweet = scrapy.Field()
    is_reply = scrapy.Field()
    is_quote = scrapy.Field()
    conversation_id = scrapy.Field()
    in_reply_to_user = scrapy.Field()
    lang = scrapy.Field()
    url = scrapy.Field()
    source_label = scrapy.Field()
    topic = scrapy.Field()
    trending_score = scrapy.Field()
    metadata = scrapy.Field()
    _is_existing = scrapy.Field()
