# Generated by Django 4.2.9 on 2026-03-07 19:44

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arxiv_id", models.CharField(max_length=50, unique=True)),
                ("title", models.TextField()),
                ("abstract", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("published_date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(max_length=1000)),
                ("pdf_url", models.URLField(blank=True, max_length=1000)),
                ("citation_count", models.IntegerField(default=0)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("key_contributions", models.TextField(blank=True)),
                ("applications", models.TextField(blank=True)),
                ("embedding_id", models.CharField(blank=True, max_length=200)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "research_papers",
                "ordering": ["-published_date"],
                "indexes": [
                    models.Index(
                        fields=["published_date"], name="research_pa_publish_bed1e3_idx"
                    ),
                    models.Index(
                        fields=["difficulty_level"],
                        name="research_pa_difficu_bedaac_idx",
                    ),
                ],
            },
        ),
    ]
