# Generated by Django 4.2.9 on 2026-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
