# Generated by Django 5.2.12 on 2026-04-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_automationworkflow_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="author_revenue_share",
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="marketplace_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="marketplace_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
