# Generated by Django 5.2.12 on 2026-04-04 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_knowledge_graph"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("mfa_enabled", "MFA Enabled"),
                            ("mfa_disabled", "MFA Disabled"),
                            ("password_changed", "Password Changed"),
                            ("api_key_created", "API Key Created"),
                            ("api_key_revoked", "API Key Revoked"),
                            ("subscription_created", "Subscription Created"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("payment_failed", "Payment Failed"),
                            ("org_created", "Org Created"),
                            ("org_member_added", "Org Member Added"),
                            ("org_member_removed", "Org Member Removed"),
                            ("document_generated", "Document Generated"),
                            ("document_deleted", "Document Deleted"),
                            ("ai_query", "AI Query"),
                            ("agent_task_created", "Agent Task Created"),
                            ("data_exported", "Data Exported"),
                            ("account_deleted", "Account Deleted"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="al_user_created_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="al_action_created_idx"
                    ),
                ],
            },
        ),
    ]
