# Generated by Django 4.2.9 on 2026-03-07 19:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechnologyTrend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("technology_name", models.CharField(max_length=200)),
                ("mention_count", models.IntegerField(default=0)),
                ("trend_score", models.FloatField(default=0.0)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField()),
                ("sources", models.JSONField(default=list)),
            ],
            options={
                "db_table": "technology_trends",
                "ordering": ["-trend_score"],
                "indexes": [
                    models.Index(fields=["date"], name="technology__date_b3b4f9_idx"),
                    models.Index(
                        fields=["category"], name="technology__categor_62259a_idx"
                    ),
                ],
                "unique_together": {("technology_name", "date")},
            },
        ),
    ]
