# Generated by Django 5.2.12 on 2026-03-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="technologytrend",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="technologytrend",
            constraint=models.UniqueConstraint(
                fields=("technology_name", "date"), name="unique_trend_per_day"
            ),
        ),
    ]
